spring.application.name=medicare
server.port=8080
server.address=0.0.0.0

#Database Connection
spring.datasource.url= jdbc:sqlserver://localhost:1433; databaseName=DBMedicare; encrypt=true; trustServerCertificate=true;sendTimeAsDatetime=false;
spring.datasource.username= sa
spring.datasource.password=1234$
spring.datasource.driver-class-name= com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# CẤU HÌNH JWT (JSON Web Token)
# ===============================
# Secret key phải là một chuỗi ngẫu nhiên dài và đủ mạnh (ít nhất 32 ký tự / 256-bit)
medicare.jwt.secret=MedicareSecretKey2024DoNotShareThisWithAnyoneBecauseItIsVeryImportant

# Thời gian sống của token tính bằng milisecond (86400000 ms = 24 giờ)
medicare.jwt.expiration=86400000

# Bật tính năng upload multipart
spring.servlet.multipart.enabled=true

# Giới hạn kích thước tối đa của 1 file (Ví dụ: 5MB)
spring.servlet.multipart.max-file-size=5MB

# Giới hạn kích thước tối đa của toàn bộ request (chứa 1 hoặc nhiều file)
spring.servlet.multipart.max-request-size=10MB

spring.servlet.multipart.location=${user.dir}/uploads
# Cấu hình đường dẫn thư mục lưu ảnh (Thư mục này sẽ tự được tạo ra trong thư mục gốc của project)
file.upload-dir=uploads/images